### PR TITLE
Add functions for smoothing surfaces and measuring Gaussian curvature

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Hi Zach @zacsimile ,

I'm just sending a PR with some functionality. I had developed it in another plugin, but not published. I think these functions would fit well here. 
* convex_hull
* laplacian_smooth
* taubin_smooth
* simplification_clustering_decimation
* colorize_curvature_apss

Furthermore, I'm suggesting to change the license of your plugin to GPL, because pymeshlab is licensed GPL. So we kind of _have to_ use GPL as well. :-/
https://github.com/cnr-isti-vclab/PyMeshLab/blob/master/LICENSE

Please let me know what you think!

Best,
Robert

### CODE REVIEW

**Comment by zacsimile** [comment]
Hi @haesleinhuepf,

Thanks so much for adding this functionality, it looks great. Is it OK if I add you as an author in `setup.cfg` to recognize your contribution on napari-hub?

The only strange thing is the tests appear to be causing problems, but I don't see a good reason why. If you have any ideas, let me know. Otherwise I will merge and have a look.

Thanks for pointing out the GPL issue, I totally spaced it. You're absolutely right we need to use GPL here.

Re: `colorize_curvature_apss`, this is great! It makes me think we should be able to plug this kind of functionality into a `color_by` menu under Colormap in the GUI. Maybe something for discussion in another issue/on zulip?

Best,
Zach

**Comment by haesleinhuepf** [comment]
Hi @zacsimile ,

> Is it OK if I add you as an author in setup.cfg to recognize your contribution on napari-hub?

I just added myself. :-D See me as a contributor, who is also happy to fix issues in case they appear. Hence, I leave the corresponding author role to you. Just le me know if there is anything.

> The only strange thing is the tests appear to be causing problems, but I don't see a good reason why. If you have any ideas, let me know. Otherwise I will merge and have a look.

Hm, the test run locally on my machine. I just pushed a speculative bugfix. If this doesn't work now, it might be easier if you merge and try to fix it. Again, I'm happy to assist.

Also just to let you know, I started a sibling to your project: [napari-process-points-and-surfaces](https://www.napari-hub.org/plugins/napari-process-points-and-surfaces). The two projects could go well together, if there wasn't the license-issue. Hence, I'd like to keep them separated. It wouldn't be the first project that is split into two repositories, just because of the licensing. Anyway, I'm just saying, you are welcome as contributor on this project as well! We can work on both together. For example, I have no readers/writers on the other side and I also don't want to reinvent the wheel. 

> Re: colorize_curvature_apss, this is great! It makes me think we should be able to plug this kind of functionality into a color_by menu under Colormap in the GUI. Maybe something for discussion in another issue/on zulip?

I try to keep "my" functions have the same name as the library they are wrapped from. That makes it easier later, when you have 20 plugins with 20 functions each ;-) Anyway, let's chat in zulip.

Thanks for maintaining this plugin! I'm sure it will have a great future!

Best,
Robert

**Comment by haesleinhuepf** [comment]
One more try 😉

**Comment by zacsimile** [comment]
Not sure what's going on, it might be a problem with my workflow script. I'm going to merge and deal with it later. Thanks so much for the contribution.

**Pull request merged**
