### PR TITLE
Updated for pymeshlab 2022.2

### PR DESCRIPTION
**Pull request by Macl-I**
Updated to account for function renaming of pymeshlab version 2022.2.
I am non expert on meshing functions, so please double check if the right ones have been implemented.

If you would like a verification from my own data do not hesitate to contact me.

### CODE REVIEW

**Comment by zacsimile** [comment]
Thanks for this update! I'd like to maintain backward compatibility with older versions of pymeshlab. Could you please wrap these changes in `try`/`except` blocks that check for an `AttributeError` on the old calls and uses these new calls in the case we receive an error?

**Comment by Macl-I** [comment]
Hey I incorporated the requested changes. 

However, I don't think they will be so relevant, since old versions of pymeshlab are not downloadable anymore via pypi, which is the reason why I had to adjust the code to get it to run in the first place. 

Let me know if any further adjustments are necessary!

**Comment by zacsimile** [comment]
Thanks! It looks to me like the old versions of `pymeshlab` are still available, but maybe I misunderstand. I thought these breaking changes happened in `pymeshlab` 2022.2. I had a look at PyPI and I can see the old versions back to 0.1.7 at https://pypi.org/project/pymeshlab/2021.10/#history. `napari` works with python 3.9+, and 0.1.7 works with python 3.9. Do these breaking changes predate 0.1.7? If so, the `except`s are not necessary.

**Comment by Macl-I** [comment]
You're welcome 😀!

Honestly I did very little checking before updating the code (which was thankfully quite easy).

I did a fresh install at python 3.9 and it didn't work out of the box and  installing an old version of pymeshlab via pip install pymeshlab==0.1.9 failed too, so I just stuck with the solution found above.

Due to the uncertainty I suggest we just stick with the try except solution just to be save.

**Comment by zacsimile** [comment]
OK. I just double-checked and it does work for me.

```
(test2) C:\Users\zach>pip install pymeshlab==0.1.9
Collecting pymeshlab==0.1.9
  Downloading pymeshlab-0.1.9-cp39-cp39-win_amd64.whl.metadata (3.6 kB)
Collecting numpy (from pymeshlab==0.1.9)
  Downloading numpy-2.0.1-cp39-cp39-win_amd64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB ? eta 0:00:00
Downloading pymeshlab-0.1.9-cp39-cp39-win_amd64.whl (28.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.6/28.6 MB 2.2 MB/s eta 0:00:00
Downloading numpy-2.0.1-cp39-cp39-win_amd64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 65.5 MB/s eta 0:00:00
Installing collected packages: numpy, pymeshlab
Successfully installed numpy-2.0.1 pymeshlab-0.1.9
```

So, yes, let's stick with the `except` to be safe. One last request, could we change it to `except AttributeError`? I prefer to avoid bare excepts.

One this is merged I'll update the tests build scripts for newer versions of python as well.

**Pull request merged**
